const FETCH_SUCCESS = "FETCH_SUCCESS";
const FETCH_ERROR = "FETCH_ERROR";
const FILTER_ALBUMS = "FILTER_ALBUMS";
const STOP_TRACK = "STOP_TRACK";
const PLAY_TRACK = "PLAY_TRACK";
const UPDATE_CURRENT_PLAYING_SONG = "UPDATE_CURRENT_PLAYING_SONG";

export {
  FETCH_SUCCESS,
  FETCH_ERROR,
  PLAY_TRACK,
  FILTER_ALBUMS,
  STOP_TRACK,
  UPDATE_CURRENT_PLAYING_SONG,
};
