// actions.js

const FETCH_SUCCESS = "FETCH_SUCCESS";
const FETCH_ERROR = "FETCH_ERROR";
const PLAY_TRACK = "PLAY_TRACK";
const FILTER_ALBUMS = "FILTER_ALBUMS";

export { FETCH_SUCCESS, FETCH_ERROR, PLAY_TRACK, FILTER_ALBUMS };
